// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAarmi557Bz_QjGfe1UidmgIZ-TYkg9hME',
    appId: '1:508674450764:web:23ef9948a80d3467ffdbe9',
    messagingSenderId: '508674450764',
    projectId: 'evently-app-c13-sun-7-pm',
    authDomain: 'evently-app-c13-sun-7-pm.firebaseapp.com',
    storageBucket: 'evently-app-c13-sun-7-pm.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBL0ktMWsUB5Y1DIZ1ba3xKrN61oe2RIw',
    appId: '1:508674450764:android:8c258b6ceb6dfdf2ffdbe9',
    messagingSenderId: '508674450764',
    projectId: 'evently-app-c13-sun-7-pm',
    storageBucket: 'evently-app-c13-sun-7-pm.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-fyA-Ls8t6cSGHv6wPyoBEFVhBjiwVPQ',
    appId: '1:508674450764:ios:2438f50653cb0f6dffdbe9',
    messagingSenderId: '508674450764',
    projectId: 'evently-app-c13-sun-7-pm',
    storageBucket: 'evently-app-c13-sun-7-pm.firebasestorage.app',
    iosBundleId: 'com.example.eventlyAppC13Sun4Pm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-fyA-Ls8t6cSGHv6wPyoBEFVhBjiwVPQ',
    appId: '1:508674450764:ios:2438f50653cb0f6dffdbe9',
    messagingSenderId: '508674450764',
    projectId: 'evently-app-c13-sun-7-pm',
    storageBucket: 'evently-app-c13-sun-7-pm.firebasestorage.app',
    iosBundleId: 'com.example.eventlyAppC13Sun4Pm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAarmi557Bz_QjGfe1UidmgIZ-TYkg9hME',
    appId: '1:508674450764:web:71f4fb4d002133e5ffdbe9',
    messagingSenderId: '508674450764',
    projectId: 'evently-app-c13-sun-7-pm',
    authDomain: 'evently-app-c13-sun-7-pm.firebaseapp.com',
    storageBucket: 'evently-app-c13-sun-7-pm.firebasestorage.app',
  );

}